### ISSUE TITLE
Problem setup with Rails

### ISSUE THREAD

**Issue by HugoGiraudel** [sighmon/mjml-rails#1]
Hello,

Thank you for your work! We are currently trying to use `mjml-rails` at Edenspiekermann, but we are facing an issue to make it work, unfortunately. :(

We manage to render the email and everything, but MJML templates are not compiled. The `<mjml-*>` tags are reaching the browser, and no compilation to HTML ever seems to happen.

![Screenshot](http://i.imgur.com/i33bE0V.png)

Here is our setup:

* ruby 2.2.0
* rails 4.2.6
* mjml-rails 2.1.1

Here is what we did:

```sh
# ./Gemfile
gem 'mjml-rails', '~> 2.1.1', require: 'mjml'
```

```ruby
# ./app/mailers/foobar_mailer.rb
class FoobarMailer < ActionMailer::Base
  def baz()
    mail(to: 'test@example.com', subject: 'test')
  end
end
```

```erb
# ./app/views/foobar_mailer/baz.mjml
<% name = 'bar' %>
<mjml>
  <mj-body>
    <mj-container>
      <mj-text>Hello <%= name %></mj-text>
    </mj-container>
  </mj-body>
</mjml>
```

```ruby
# ./app/spec/mailers/previews/foobar_mailer_preview.rb
class FoobarMailerPreview < ActionMailer::Preview
  def baz
    FoobarMailer.baz
  end
end
```

```ruby
# ./config/routes.rb
if Rails.env.development?
    get '/rails/mailers'       => "rails/mailers#index"
    get '/rails/mailers/*path' => "rails/mailers#preview"
end
```

Note that we did correctly install the `mjml` npm package globally.

Any idea what’s happening? Ping my colleague @pgoetze.

**Comment by sighmon** [comment]
@HugoGiraudel @pgoetze Oh right, in `foobar_mailer.rb` try this:

```ruby
# ./app/mailers/foobar_mailer.rb
class FoobarMailer < ActionMailer::Base
  def baz()
    mail(to: 'test@example.com', subject: 'test') do |format|
      format.text
      format.mjml
    end
  end
end
```

I'll add that to the README if it solves your problem.

**Comment by HugoGiraudel** [comment]
Hey, it seems to work, thanks!

Do you have any idea why a partial render does not crash but outputs nothing?

```erb
<%= render partial: 'need_link' %>
```

Also tried:

```erb
<%= render 'need_link' %>
```

Also tried:

```erb
<%= render partial: 'need_link', formats: [:mjml] %>
```

The partial does not print anything. :(

**Comment by HugoGiraudel** [comment]
My bad, the formats should be `[:html]`. I misread the docs. Thanks! :x

**Comment by sighmon** [comment]
@HugoGiraudel glad it's working for you now. Feel free to make improvements. :-)

**Comment by manuelmeurer** [comment]
I had the exact opposite problem as OP. 😄 
When I write
```
mail to: 'test@example.com', subject: 'test' do |format|
  format.text
  format.mjml
end
```
Rails can't find the template. When I just write `mail to: 'test@example.com', subject: 'test'` it works fine. Maybe a change in a recent version? I'm on v2.2.0.

**Comment by sighmon** [comment]
@manuelmeurer that's a known bug we're trying to find an elegant solution for at the moment. @thatpixguy has an ugly hack that gets around it for now.. did you want to post that here Pix?

Just out of interest, what folder are your views in @manuelmeurer ?

**Comment by manuelmeurer** [comment]
I put my views in a `mailers` folder, maybe that's the issue?

```
class ApplicationMailer < ActionMailer::Base
  def self.inherited(subclass)
    subclass.default template_path: "mailers/#{subclass.name.to_s.underscore}"
  end
end
```

**Comment by sighmon** [comment]
@manuelmeurer @HugoGiraudel Try this and let me know how you get along:

```ruby 
    lookup_context.view_paths = ["test/views/template_subdir"]
    mail( to: 'test@example.com', subject: 'test' ) do |format|
      format.text
      format.mjml
    end
```

**Comment by manuelmeurer** [comment]
Well, I'm actually happy with the way it works right now (without needing the block at all). 😄
