### ISSUE TITLE
Working locally but not in Heroku

### ISSUE THREAD

**Issue by raulsann** [sighmon/mjml-rails#10]
Hi,

We've followed the instructions by:
- adding the gem: 
  `gem 'mjml-rails'`
- installing it
  `bundle install`

and creating the buildpacks. This is the output of `heroku buildpacks`:

```
1. heroku/nodejs
2. heroku/ruby
```

It works great locally, but when trying to run it in heroku, it does not raise any error, it simply sends the email in mjml markup, without being interpreted. 

Any leads about why the mjml markup is not translated into html in heroku? 

Thanks!

**Comment by sighmon** [comment]
@raulsann I've just updated the gem to use MJML v3, is there a chance your ```package.json``` file hasn't been updated?

```json
"dependencies": {
    "mjml": "^3.0"
  },
```
