### ISSUE TITLE
Add config option for fonts

### ISSUE THREAD

**Issue by clairezed** [sighmon/mjml-rails#111]
Hello,

Apparently, there is a config option in mjml that prevents google fonts import when we do not want it : https://github.com/mjmlio/mjml/issues/216#issuecomment-1063194602

It seems to me the easiest workaround for user among those refered to here :https://github.com/sighmon/mjml-rails/issues/13#issuecomment-274238431.

Is there a way to add it in mjml-rails config ?

Thanks for your work !

**Comment by sighmon** [comment]
@clairezed Hi there, we should be able to add it to the initialiser as we've done for [minify](https://github.com/search?q=repo%3Asighmon%2Fmjml-rails%20minify&type=code). Would you like to put a pull request together for it?

```ruby
# config/initializers/mjml.rb
Mjml.setup do |config|
  # disable fonts
  config.fonts = {}
end
```
