### ISSUE TITLE
Request out to google fonts for Ubuntu font necessary when using Webmock.

### ISSUE THREAD

**Issue by skunkworker** [sighmon/mjml-rails#13]
I ran into this issue when running tests that would send emails. I'm using webmock to stub out the requests and it seems like `mjml` pulls in the `Ubuntu` font from google fonts api. After spending some time on a strange error inside of `premailer-rails` I figured out what `mjml-rails` needed to get it working.
The following gist has a webmock response.
https://gist.github.com/skunkworker/c7d4cc065bdeaafa71307f18652f00c4

Is there an easier way to disable this for tests?

**Comment by sighmon** [comment]
@skunkworker Sorry, I don't have any experience with webmock. Might [VCR](https://github.com/vcr/vcr) do what you want?

**Comment by skunkworker** [comment]
I got it working by stubbing out the request to use the ubuntu font. Is that a forced part of `mjml`?

**Comment by sighmon** [comment]
@skunkworker looks like [it is](https://github.com/mjmlio/mjml/issues/216). But there are workarounds.
