### ISSUE TITLE
Can't seem to handle files named .html.erb

### ISSUE THREAD

**Issue by raderj89** [sighmon/mjml-rails#14]
I'm experimenting with MJML, incorporating it into existing emails we have, just converting a couple partials to MJML so I don't have to convert everything to MJML at once. Some of our email view files end in .erb, and when I call `format.mjml`, it renders without any issue. However, some email views end in .html.erb, and calling `format.mjml` results in a `ActionView::Template::Error: Missing template` error. Curious if there's a way to address this.

**Comment by ramaboo** [comment]
I have similar issues. The handling of templates in this gem is all wrong. For example something.mjml.slim should work so should something.mjml.slim.erb. Rails is supposed to chain templates where each one renders and passes it down the line. Somehow though this gem does not do that correctly. I have been fighting with it for awhile now :(

**Comment by sighmon** [comment]
@raderj89 @ramaboo I'm short of time at the moment, so if either or both of you would like to propose a fix and submit a pull request that'd be great! :-)

**Comment by pablocrivella** [comment]
Any updates about this issue?

**Comment by sighmon** [comment]
@pablocrivella Could you post some sample code of your controller/mailers, views, where they sit in your filesystem, and the errors. Thanks!

**Comment by pablocrivella** [comment]
I'm using it to style devise mailers, so my code is exactly like [this](https://github.com/sighmon/mjml-rails#sending-devise-user-emails).
I normally use `slim` on all my files, so i tried to make this:
```
app/views/devise/mailer/reset_password_instructions.mjml.slim
```

But that throws an  exception

**Comment by sighmon** [comment]
@pablocrivella have you tried without .slim? So just ```app/views/devise/mailer/reset_password_instructions.mjml``` but still using slim markup?

**Comment by pablocrivella** [comment]
@sighmon haven't tried that, i'll do that and let you know.

**Comment by ruinunes** [comment]
In order to use haml templates, I've added an initializer file, specifying `template_language`:
```ruby
Mjml.setup do |config|
  config.template_language = :haml
end
```

This allows to deliver an email for a filename as `some_template.mjml`, using haml syntax. This is not very optimal, as code editors won't highlight the haml syntax by looking at the file extension.
Calling the `some_template.mjml.haml`, will highlight the haml syntax on an editor, but the email will be delivered as text.
