### ISSUE TITLE
Gem Load Error on Heroku review app

### ISSUE THREAD

**Issue by sianglim** [sighmon/mjml-rails#15]
Hi @sighmon,

I'm having an issue when deploying a branch to Heroku's review apps.

The key errors I see are:
`  Bundler::GemRequireError: There was an error while trying to load the gem 'mjml-rails'`
`Gem Load Error is: undefined method `chomp' for nil:NilClass`
`NoMethodError: undefined method `chomp' for nil:NilClass
`/tmp/.../.../vendor/bundle/ruby/2.1.0/gems/mjml-rails-2.4.1/lib/mjml.rb:25:in `discover_mjml_bin'`

I've set heroku to run the nodejs buildpack first.

On the CI platform, I have `npm install` as the first build instruction, but it feels like it's not triggering it. The strange thing is that it works on production.

Hope you can point out where I'm going wrong. 😃

**Comment by sighmon** [comment]
@sianglim Are you sure ```npm``` is installing okay? Because ```npm bin``` is returning nil, which is why chomp is failing. So perhaps try some logging to see if any basic npm commands are running.

**Comment by sianglim** [comment]
Thanks for taking the time to look into this @sighmon.

It turns out that heroku's `app.json` didn't have the nodejs buildpack added.
