### ISSUE TITLE
No plain text version

### ISSUE THREAD

**Issue by caitlin** [sighmon/mjml-rails#22]
Normally with Rails, I can drop in both a `html.erb` and a `text.erb` template and it compiles into a multipart email with an HTML version and a plain text version. 

I can't figure out how to include my plain text version in my emails with this. Is it not supported or am I missing a connection piece?

**Comment by sighmon** [comment]
Hi @caitlin,
In my app I'm sending multipart emails with both HTML & plain text, the filenames are:
```signup_confirmation.mjml``` and ```signup_confirmation.text.erb```
Does that help/work for you?
Best, Simon.

**Comment by caitlin** [comment]
Hi Simon, 
Yeah, that helped! I had tried that (and all other variations of extensions), but I think my layout file was messing with it. Once I put the whole template in a mjml (with no layout), it started to pull in the plain text.

Thanks!

**Comment by sighmon** [comment]
@caitlin oh fantastic. If you can think of a way to improve the gem to make it work more closely to the way you expected it, please don't hesitate to make a pull request.

Best, Simon.
