### ISSUE TITLE
Library doesn't support MJML 4.x

### ISSUE THREAD

**Issue by Polidoro** [sighmon/mjml-rails#25]
As far as I can tell this library doesn't support MJML 4.x, instead you get this error which is confusing:

Couldn't find the MJML binary.. have you run $ npm install mjml?

Can be fixed by installing mjml ^3.0 but it is worth mentioning in the docs or improving the error msg.

**Comment by sighmon** [comment]
@Polidoro Sorry about that - @jipiboily had done all the hard work, but I was slow on pushing the changes.

`mjml-rails 4.0.0` should be with rubygems soon, let me know how that works for you, and if the documentation needs updating.

**Comment by Polidoro** [comment]
Hey thanks for the prompt reply! Totally understandable, just wanted to get that error message somewhere that it might show up in search results in case someone else was having the same problem I was.

Thanks for the great library!

**Comment by sighmon** [comment]
Added a better error message that includes the MJML binary version that's expected, see this commit: d44138baa829bdf079ead586f086fd5ea15dc28b
