### ISSUE TITLE
Minification of output files

### ISSUE THREAD

**Issue by tomasmcm** [sighmon/mjml-rails#28]
Mjml cli allows files to be minified automatically using `--config.beautify false --config.minify true`. The defaults are `--config.beautify true --config.minify false`.

Can you add a config option to the gem so that it is possible to change the default to minify the output?

**Comment by sighmon** [comment]
@tomasmcm sounds good. I don't have dev time for it now, would you like to submit a pull request?

**Comment by sighmon** [comment]
Fixed by @mandyhuang 👍
