### ISSUE TITLE
rails mailer previews render as text with mjml tags

### ISSUE THREAD

**Issue by voordev** [sighmon/mjml-rails#44]
When making /rails/mailers previews with option for mjml and failback text format rendering.
The rendered text/plaintext format emails show the mjml tags and not just the text.

**Comment by sighmon** [comment]
@voordev do you have any example code or an example repository showing the bug?

**Comment by voordev** [comment]
@DaddyWozBucks 
I Currently use 

```layout "mailer" ```
Does specifying the full filename to the layout file works but like my example not?
