### ISSUE TITLE
Problem with mime-types using turbolinks

### ISSUE THREAD

**Issue by jameslafa** [sighmon/mjml-rails#5]
When using turbolinks to sign_in with devise, I have the following error:

``` ruby
ActionController::MissingRenderer in Devise::SessionsController#new
No renderer defined for format: mjml
```

```
responders (2.2.0) lib/action_controller/responder.rb:211:in `api_behavior'
responders (2.2.0) lib/action_controller/responder.rb:193:in `rescue in to_format'
responders (2.2.0) lib/action_controller/responder.rb:185:in `to_format'
responders (2.2.0) lib/action_controller/responder.rb:163:in `respond'
responders (2.2.0) lib/action_controller/responder.rb:156:in `call'
responders (2.2.0) lib/action_controller/respond_with.rb:205:in `respond_with'
devise (4.1.1) app/controllers/devise/sessions_controller.rb:12:in `new'
actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.6) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.6) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.6) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
```

I'm not sure how it exactly works, but I suspect that rails is trying to find out how to respond based on the MimeType which is `text/html`. Mjml-rails register also :mjml as `text/html` and it seems to create some kind of conflict. If I remove the minme-type registration inside Mjml-rails, then everything works fine, but the emails have the wrong MimeType.

I sent hours on it, but couldn't find any solution. Do you have any idea?

**Comment by jameslafa** [comment]
So I kept investigating and I realised that actually it was not only in devise, but everywhere on my website when navigating with Turbolinks. I'm still surprised to be the only one having this problem.

My intuition was that when you register the MimeType :mjml (see below), :mjml become the default format for "text/html". It's probably a question of order of the formats associated with the Mime::Type "text/html".

````ruby
Mime::Type.register "text/html", :mjml
````

I solved the problem by filling the `config/initializers/mime_types.rb` which is it seems by default empty in Rails 4.2

Here is the content I added:

````ruby
Mime::Type.register "*/*", :all
Mime::Type.register "text/plain", :text, [], %w(txt)
Mime::Type.register "text/html", :html, %w( application/xhtml+xml ), %w( xhtml )
Mime::Type.register "text/javascript", :js, %w( application/javascript application/x-javascript )
Mime::Type.register "text/css", :css
Mime::Type.register "text/calendar", :ics
Mime::Type.register "text/csv", :csv
Mime::Type.register "application/xml", :xml, %w( text/xml application/x-xml )
Mime::Type.register "application/rss+xml", :rss
Mime::Type.register "application/atom+xml", :atom
Mime::Type.register "application/x-yaml", :yaml, %w( text/yaml )

Mime::Type.register "multipart/form-data", :multipart_form
Mime::Type.register "application/x-www-form-urlencoded", :url_encoded_form

# http://www.ietf.org/rfc/rfc4627.txt
# http://www.json.org/JSONRequest.html
Mime::Type.register "application/json", :json, %w( text/x-json application/jsonrequest )  
````

The first line is the one that matter I guess. By doing this, the "text/html" Mime::Type has by default the :html format and not :mjml, which is register later and has a lower priority.

Have you tested the gem on Rails 4.2?

Do you know a way to register the format :mjml without making it default for "text/html"?
Maybe something like this would do the trick:

````ruby
Mime::Type.register "text/html", :html, %w( application/xhtml+xml ), %w( xhtml ), :mjml
````

However, I don't know what are the consequence if the Mime::Type is already registered for example.

If you have an idea, let me know, I will do a pull-request with pleasure.

**Comment by cerdiogenes** [comment]
I have a suggestion here: don't worry with mimetypes and remove the line `Mime::Type.register "text/html", :mjml`

Instead of having `/app/views/user_mailer/email.mjml` we could name it `/app/views/user_mailer/email.html.mjml` and don't have to worry with format when sending email. In the end mjml is something to be converted to html. This also involves changing https://github.com/sighmon/mjml-rails/blob/master/lib/mjml.rb#L38 to `if template.formats.include?(:html)`

@sighmon I don't know if this will solve this issue, but is a modification that pleases me, since I think it's more convention over configuration.

**Comment by sighmon** [comment]
@jameslafa @cerdiogenes I was wondering if registering `Mime::Type.register "text/html", :miml` was the right thing to do, so thanks for investigating @jameslafa and @cerdiogenes 's solution sounds great.

It'd be ideal if the change going from `email.mjml` to `email.mjml.html` could still be backwards compatible with the current version of the gem, so that might need a bit more work. But please do submit pull requests and we can test and work on the best solution going forwards.

I haven't looked into it yet, but noticed [register_alias](http://api.rubyonrails.org/classes/Mime/Type.html#method-c-register_alias) a while back, so that's something else that may or may not work here.

**Comment by sighmon** [comment]
@jameslafa @cerdiogenes Is this fixed now with @tylerhunt 's register_alias fix in ```v2.4.0```

**Comment by jameslafa** [comment]
@sighmon I'll test it and let you know.
@tylerhunt thanks for the patch!

**Comment by jameslafa** [comment]
Sorry for the late reply. I've updated it and I don't have any problem anymore.
Thanks for the fix!
