### ISSUE TITLE
Yarn bin command no longer functions as it is used in lib/mjml.rb

### ISSUE THREAD

**Issue by liamelliott** [sighmon/mjml-rails#63]
Running `yarn bin` as used in the lib/mjml.rb file no longer returns a bin directory, but a list of available binaries. In newer versions of Yarn, you must run `yarn bin mjml` to get a direct path to the binary. I'll take this as a PR if nobody else is able to.

**Comment by sighmon** [comment]
@liamelliott That'd be great if you could, and keep it backwards compatible for older versions of `yarn` too.

**Comment by liamelliott** [comment]
Sweet! I'll try and get on that this week sometime.

**Comment by doits** [comment]
I think I fixed it by using `yarn run mjml` when installed with yarn in #66 – I think this is the proper way to run binaries by yarn anyway and with it it should work with yarn v2, too.
