### ISSUE TITLE
Mjml 3.0 is not compatible

### ISSUE THREAD

**Issue by Uelb** [sighmon/mjml-rails#8]
Problem with mjml version 3.0
The gem checks that mjml is set up to the ~2.0 version : https://github.com/sighmon/mjml-rails/blob/master/lib/mjml.rb#L11
However, there has been a release of the 3.0 version recently

**Comment by sighmon** [comment]
@Uelb Thanks for the nudge.. I've updated it to support MJML 3.x now. :-)
