### ISSUE TITLE
image_tag helper in MJML template

### ISSUE THREAD

**Issue by victordarras** [sighmon/mjml-rails#82]
Hi,
I'd like to use a standard rails `image_tag` in my template, but MJML seems to ignore it, am I doing it wrong ?

```
<mjml>
  <mj-body>
    <mj-section >
      <mj-column>
        <%= image_tag('logo_colored_horiz.png', width: "120" ) %>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by victordarras** [comment]
Nevermind, I found another solution that work perfectly with :

`<mj-image src="<%= image_url('logo_colored_horiz.png') %>" width="120">`

**Comment by sighmon** [comment]
@victordarras Nice one, that's how I call images and other assets too.
