### ISSUE TITLE
RuboCop?

### ISSUE THREAD

**Issue by der-flo** [sighmon/mjml-rails#89]
Are you interested in integrating RuboCop in your Gem?

I'm willing to create a pull request containing a RuboCop setup and fixes for all offenses in the existing code. I would start with the default RuboCop configuration which seems common sense in the community.

**Comment by sighmon** [comment]
@der-flo That would be amazing thank you! We could also add it to the GitHub [Action](https://github.com/sighmon/mjml-rails/blob/master/.github/workflows/test.yml) before the tests run.

**Comment by der-flo** [comment]
It's on my list for the coming friday. Stay tuned.
