### ISSUE TITLE
`Mjml::Parser#render` suppresses errors in case of Tempfile exceptions

### ISSUE THREAD

**Issue by der-flo** [sighmon/mjml-rails#90]
In case of an exception in `Tempfile.open` the `in_tmp_file` in the current [`ensure` block](https://github.com/sighmon/mjml-rails/blob/master/lib/mjml/parser.rb#L18) is `nil`, which lets to another exception when calling `unlink`. This shadows the original exception.

We encountered this issue in context of a Docker environment and fixed this via a monkey patch.

Are you interested in a pull request, ideally with a test case?

**Comment by sighmon** [comment]
@der-flo A PR with a test case would be excellent thanks.

**Comment by der-flo** [comment]
It's on my list for the coming friday. Stay tuned.
