### ISSUE TITLE
Exit code in case of an error when calling the mjml binary

### ISSUE THREAD

**Issue by der-flo** [sighmon/mjml-rails#91]
We ran into issues when calling out to the mjml binary. Our Docker environment sometimes kills the child process because of limited memory. In the case the process fails silently. We were able to debug this with a monkey patch adding the exit code to the [ParseError](https://github.com/sighmon/mjml-rails/blob/master/lib/mjml/parser.rb#L38).

Are you interested in a pull request adding this debug information?

**Comment by sighmon** [comment]
@der-flo Adding debug to the ParseError sounds excellent too. Yes please.

**Comment by der-flo** [comment]
It's on my list for the coming friday. Stay tuned.

**Comment by der-flo** [comment]
Christmas is coming, I‘ll prepare this in january.
